// This file will be auto-generated by: npx supabase gen types typescript
// For now, use a minimal placeholder.

export type Database = {
  public: {
    Tables: Record<string, unknown>;
    Views: Record<string, unknown>;
    Functions: Record<string, unknown>;
    Enums: Record<string, unknown>;
  };
};
